proxies:
  - name: sg3.6n6.net
    server: sg3.6n6.net
    port: 443
    type: trojan
    password: e47d24e0-dca1-11ef-bf1a-1239d0255272
    skip-cert-verify: true
    sni: bimbel.ruangguru.com
    network: ws
    ws-opts:
      path: /howdy
      headers:
        Host: sg3.6n6.nett
    udp: true
